# Generated by Django 5.2.1 on 2026-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due')], default='free', max_length=20),
        ),
    ]
