# Generated by Django 5.2.1 on 2026-03-05 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumitem',
            name='file_attachment',
        ),
        migrations.AddField(
            model_name='premiumitem',
            name='additional_files',
            field=models.JSONField(blank=True, default=list, help_text='List of additional file URLs'),
        ),
        migrations.AddField(
            model_name='premiumitem',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to='premium/code/'),
        ),
        migrations.AddField(
            model_name='premiumitem',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video Tutorial'), ('pdf', 'PDF Guide'), ('code', 'Code Bundle'), ('template', 'Template Pack'), ('tool', 'Software Tool')], default='article', max_length=20),
        ),
        migrations.AddField(
            model_name='premiumitem',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='premium/pdfs/'),
        ),
        migrations.AddField(
            model_name='premiumitem',
            name='video_duration',
            field=models.CharField(blank=True, help_text="e.g., '15:30'", max_length=20),
        ),
        migrations.AddField(
            model_name='premiumitem',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='premium/videos/'),
        ),
        migrations.AddField(
            model_name='premiumitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL'),
        ),
        migrations.AlterField(
            model_name='premiumcategory',
            name='color',
            field=models.CharField(default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='premiumcategory',
            name='icon',
            field=models.CharField(default='fa-star', max_length=50),
        ),
        migrations.AlterField(
            model_name='premiumitem',
            name='content',
            field=models.TextField(blank=True, help_text='Main content text'),
        ),
        migrations.AlterField(
            model_name='premiumitem',
            name='file_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.IntegerField(default=0)),
                ('last_position', models.CharField(blank=True, help_text='Video timestamp or page number', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.premiumitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
