# Generated by Django 5.2.1 on 2026-03-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_premiumitem_file_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumitem',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
