# Generated by Django 5.2.1 on 2026-03-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='button_text',
            field=models.CharField(default='Choose Plan', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='highlight_color',
            field=models.CharField(default='primary', help_text='Bootstrap color class: primary, success, info, warning, danger', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured on homepage'),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.IntegerField(default=0, help_text='Number of trial days (0 = no trial)'),
        ),
    ]
