# Generated by Django 5.2.1 on 2026-03-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plan_billing_cycle_plan_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='highlight_color',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='trial_days',
        ),
    ]
